### ISSUE TITLE
Build Errors CS8627

### ISSUE THREAD

**Issue by mrs01dev** [cloudtoid/framework#5]
Could you please fix those errors :
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	65	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	79	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	95	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	113	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	125	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	374	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	374	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	386	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Contract	 Cloudtoid.Framework\Contract\Contract.cs	386	Active
Error	CS8627	A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.	Cloudtoid.Framework	 Cloudtoid.Framework\Extensions	 Cloudtoid.Framework\Extensions\EnumerableExtensions.cs	31	Active
Error	CS0234	The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	Cloudtoid.Framework	 Cloudtoid.Framework\String	 Cloudtoid.Framework\String\StringValuesExtensions.cs	4	Active
Error	CS0246	The type or namespace name 'StringValues' could not be found (are you missing a using directive or an assembly reference?)	Cloudtoid.Framework	 Cloudtoid.Framework\String	 Cloudtoid.Framework\String\StringValuesExtensions.cs	20	Active

**Comment by prezaei** [comment]
Hey, I am not seeing this. Can you try and repro it?
